In [3]:
pwd

'C:\\Users\\user\\Pandas tutorial'

In [4]:
cd c:/Users/User/OneDrive/Desktop

c:\Users\User\OneDrive\Desktop

In [6]:
df = pd.read_csv("datasets-uci-iris.csv",nrows = 25)
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
5    4.6  3.4  1.4  0.3     Iris-setosa
6    5.0  3.4  1.5  0.2     Iris-setosa
7    4.4  2.9  1.4  0.2     Iris-setosa
8    4.9  3.1  1.5  0.1     Iris-setosa
9    5.4  3.7  1.5  0.2     Iris-setosa
10   4.8  3.4  1.6  0.2     Iris-setosa
11   4.8  3.0  1.4  0.1     Iris-setosa
12   4.3  3.0  1.1  0.1     Iris-setosa
13   5.8  4.0  1.2  0.2     Iris-setosa
14   5.7  4.4  1.5  0.4     Iris-setosa
15   5.4  3.9  1.3  0.4     Iris-setosa
16   5.1  3.5  1.4  0.3     Iris-setosa
17   5.7  3.8  1.7  0.3     Iris-setosa
18   5.1  3.8  1.5  0.3     Iris-setosa
19   5.4  3.4  1.7  0.2     Iris-setosa
20   5.1  3.7  1.5  0.4     Iris-setosa
21   4.6  3.6  1.0  0.2     Iris-setosa
22   5.1  3.3  1.7  0.5     Iris-setosa
23   4.8  3.4  1.9  0.2     Iris-setosa
24   5.0  3.0  1.6  0.2     Iris-setosa
25   5.0  3.4  1.6  0.4     Iris-setosa
26   5.2  3.5  1.5  0.2     Iris-setosa
27   5.2  3.4  1.4  0.2     Iris-setosa
28   4.7  3.2  1.6  0.2     Iris-setosa
29   4.8  3.1  1.6  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
119  6.9  3.2  5.7  2.3  Iris-virginica
120  5.6  2.8  4.9  2.0  Iris-virginica
121  7.7  2.8  6.7  2.0  Iris-virginica
122  6.3  2.7  4.9  1.8  Iris-virginica
123  6.7  3.3  5.7  2.1  Iris-virginica
124  7.2  3.2  6.0  1.8  Iris-virginica
125  6.2  2.8  4.8  1.8  Iris-virginica
126  6.1  3.0  4.9  1.8  Iris-virginica
127  6.4  2.8  5.6  2.1  Iris-virginica
128  7.2  3.0  5.8  1.6  Iris-virginica
129  7.4  2.8  6.1  1.9  Iris-virginica
130  7.9  3.8  6.4  2.0  Iris-virginica
131  6.4  2.8  5.6  2.2  Iris-virginica
132  6.3  2.8  5.1  1.5  Iris-virginica
133  6.1  2.6  5.6  1.4  Iris-virginica
134  7.7  3.0  6.1  2.3  Iris-virginica
135  6.3  3.4  5.6  2.4  Iris-virginica
136  6.4  3.1  5.5  1.8  Iris-virginica
137  6.0  3.0  4.8  1.8  Iris-virginica
138  6.9  3.1  5.4  2.1  Iris-virginica
139  6.7  3.1  5.6  2.4  Iris-virginica
140  6.9  3.1  5.1  2.3  Iris-virginica
141  5.8  2.7  5.1  1.9  Iris-virginica
142  6.8  3.2  5.9  2.3  Iris-virginica
143  6.7  3.3  5.7  2.5  Iris-virginica
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [9]:
df = pd.read_csv("datasets-uci-iris.csv",nrows = 25)
df

    5.1  3.5  1.4  0.2  Iris-setosa
0   4.9  3.0  1.4  0.2  Iris-setosa
1   4.7  3.2  1.3  0.2  Iris-setosa
2   4.6  3.1  1.5  0.2  Iris-setosa
3   5.0  3.6  1.4  0.2  Iris-setosa
4   5.4  3.9  1.7  0.4  Iris-setosa
5   4.6  3.4  1.4  0.3  Iris-setosa
6   5.0  3.4  1.5  0.2  Iris-setosa
7   4.4  2.9  1.4  0.2  Iris-setosa
8   4.9  3.1  1.5  0.1  Iris-setosa
9   5.4  3.7  1.5  0.2  Iris-setosa
10  4.8  3.4  1.6  0.2  Iris-setosa
11  4.8  3.0  1.4  0.1  Iris-setosa
12  4.3  3.0  1.1  0.1  Iris-setosa
13  5.8  4.0  1.2  0.2  Iris-setosa
14  5.7  4.4  1.5  0.4  Iris-setosa
15  5.4  3.9  1.3  0.4  Iris-setosa
16  5.1  3.5  1.4  0.3  Iris-setosa
17  5.7  3.8  1.7  0.3  Iris-setosa
18  5.1  3.8  1.5  0.3  Iris-setosa
19  5.4  3.4  1.7  0.2  Iris-setosa
20  5.1  3.7  1.5  0.4  Iris-setosa
21  4.6  3.6  1.0  0.2  Iris-setosa
22  5.1  3.3  1.7  0.5  Iris-setosa
23  4.8  3.4  1.9  0.2  Iris-setosa
24  5.0  3.0  1.6  0.2  Iris-setosa

In [12]:
df = pd.read_csv("datasets-uci-iris.csv",nrows = 25, names =["W","X","Y","Z","A"] )
df

      W    X    Y    Z            A
0   5.1  3.5  1.4  0.2  Iris-setosa
1   4.9  3.0  1.4  0.2  Iris-setosa
2   4.7  3.2  1.3  0.2  Iris-setosa
3   4.6  3.1  1.5  0.2  Iris-setosa
4   5.0  3.6  1.4  0.2  Iris-setosa
5   5.4  3.9  1.7  0.4  Iris-setosa
6   4.6  3.4  1.4  0.3  Iris-setosa
7   5.0  3.4  1.5  0.2  Iris-setosa
8   4.4  2.9  1.4  0.2  Iris-setosa
9   4.9  3.1  1.5  0.1  Iris-setosa
10  5.4  3.7  1.5  0.2  Iris-setosa
11  4.8  3.4  1.6  0.2  Iris-setosa
12  4.8  3.0  1.4  0.1  Iris-setosa
13  4.3  3.0  1.1  0.1  Iris-setosa
14  5.8  4.0  1.2  0.2  Iris-setosa
15  5.7  4.4  1.5  0.4  Iris-setosa
16  5.4  3.9  1.3  0.4  Iris-setosa
17  5.1  3.5  1.4  0.3  Iris-setosa
18  5.7  3.8  1.7  0.3  Iris-setosa
19  5.1  3.8  1.5  0.3  Iris-setosa
20  5.4  3.4  1.7  0.2  Iris-setosa
21  5.1  3.7  1.5  0.4  Iris-setosa
22  4.6  3.6  1.0  0.2  Iris-setosa
23  5.1  3.3  1.7  0.5  Iris-setosa
24  4.8  3.4  1.9  0.2  Iris-setosa

In [14]:
df.to_csv("new.csv",columns =['W','X','Y'] )

## Aman_review : This is a markdown to write details about specific parts of a notebook in human readable english language. This helps others to understand the script.

In [7]:
"""
You should write comments at top of each cell like this to tell others what are you doing in each cell.
Always remember I am looking at your code you have to make it clear, consize and easy to read. You can also look at 
github how others write code and try to write like them.

I am writing bigger comments in this notebook because I want you as a novice to understand usually I would just write 
two or three words.
"""

# Import modules required in this noptebook
from sklearn import datasets #this contains few datasets already builtin you can see I am not reading csv file
import pandas as pd
import numpy as np

In [10]:
dir(datasets) #this is to show you list of things you can do with datasets

""" I am using plain english language because you are a beginner profesionally I would say I am showing you - 
attributes of dataset object.
You should try to understand fundamentals of object oriented programming as this is most important part to 
write software without it you should not consider yourself a software developer.
I usually listen to youtube videos and talks about python, you can find millions of videos about python on youtube.
when you are not coding or are free try to watch these amazing talks and videos.

free code camp course https://www.youtube.com/watch?v=rfscVS0vtbw
pydata https://www.youtube.com/user/PyDataTV (This is very good resource to update oneself about whats new)
"""

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_svmlight_format',
 'base',
 'california_housing',
 'clear_data_home',
 'covtype',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_mldata',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'kddcup99',
 'lfw',
 'load_boston',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_mlcomp',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_circles',
 'make_classification',
 'make_friedman1',
 'make_friedman2',
 'make_friedman3',
 'make_gaussian_quantiles',
 'make_hastie_10_2',
 'make_low_rank_matrix',
 'make_moons',
 'make_multilabel_classification',
 'make_regression',
 'make_s_curve',
 'make_sparse_coded_signal',
 'make_sparse_spd_matrix',
 'make_sparse_uncorrelated',
 'make_spd_matrix',
 'make_swiss_roll',
 'mlcomp',
 'mldata',
 'mldata_filename',
 'olivetti_faces',
 'openml',
 'rcv1',
 'samples_generator',
 'species_distributions',
 'svmlight_format',
 'twenty_newsgroups']

In [11]:
iris = load_iris()  # this will give you an error try to understand the error

"""
It says NameError: name 'load_iris' is not defined and shows where error occured using ----> 1 iris = load_iris()

You should try to understand where error occured and what is the error.
It says name not defined because python searched the file above this cell and didn't find this function.
Below I show how to access load_iris
"""

NameError: name 'load_iris' is not defined

In [2]:
# Here I am loading dataset see load_iris is available in list above.
"""
To access load_iris I have to specify where is load iris. It is in datasets object. So I wrote datasets.load_iris()
"""
iris = datasets.load_iris()

In [13]:
from sklearn.datasets import load_iris

In [14]:
iris_loaded_without_specifying_datasets = load_iris()
""" Now it worked earlier it gave an error"""

In [8]:
# Now pandas is a datastructure in python other datastructures are dictionaries, list, tuple, numpy array etc.
# read and practice about data structures here https://python.swaroopch.com/data_structures.html
data_ = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])

In [9]:
# this shows the head of data_ object which is a pandas dataframe/datastructure
data_.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0.0
1,4.9,3.0,1.4,0.2,0.0
2,4.7,3.2,1.3,0.2,0.0
3,4.6,3.1,1.5,0.2,0.0
4,5.0,3.6,1.4,0.2,0.0

In [15]:
# to see things you can do with this onject like you saw with datasets earlier call dir function and in brackets
# give the name of object you want to see the list of attributes
dir(data_)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_SLICEMAP',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_wrap__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__unicode__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_only_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_box_col_values',
 '_box_item_values',
 '_builtin_table',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_percentile',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_combine_const',
 '_combine_frame',
 '_combine_match_columns',
 '_combine_match_index',
 '_compare_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_for_slice',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_create_indexer',
 '_cython_table',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_expand_axes',
 '_find_valid_index',
 '_from_arrays',
 '_from_axes',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_getitem_array',
 '_getitem_column',
 '_getitem_frame',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_iget_item_cache',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_dict',
 '_init_mgr',
 '_init_ndarray',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_cython_func',
 '_is_datelike_mixed_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_join_compat',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_axis',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_setup_axes',
 '_shallow_copy',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_frame_compat',
 '_unpickle_matrix_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'as_matrix',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'axes',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'clip_lower',
 'clip_upper',
 'columns',
 'combine',
 'combine_first',
 'compound',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'from_dict',
 'from_records',
 'ftypes',
 'ge',
 'get',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_values',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'ix',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_axis',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'target',
 'to_clipboard',
 'to_csv',
 'to_dense',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_msgpack',
 'to_panel',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sparse',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'values',
 'var',
 'where',
 'xs']

In [16]:
data_.describe() #look at statistics to know about data

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

In [ ]:
"""Now go pandas official doc to http://pandas.pydata.org/pandas-docs/version/0.23/ and try to use functions mentioned there.
You will use this website all the time so make sure you know this website very well. This is the most important resource
to know about pandas.
"""

In [18]:
data_.tail()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
145,6.7,3.0,5.2,2.3,2.0
146,6.3,2.5,5.0,1.9,2.0
147,6.5,3.0,5.2,2.0,2.0
148,6.2,3.4,5.4,2.3,2.0
149,5.9,3.0,5.1,1.8,2.0

In [20]:
# Here you can see I am using a combination of functions .groupby and .mean in one command This is how one should do
# rather than writing two different commands
data_.groupby('target').mean()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
target,,,,
0.0,5.006,3.428,1.462,0.246
1.0,5.936,2.770,4.260,1.326
2.0,6.588,2.974,5.552,2.026

In [21]:
""" Here I am showing few concepts of python programming
I am calling function .head on data_ object and passing an argument of 10
This resulted in showing me top 10 rows of data If you call it without passing 10 it prints 5 rows by default
"""
data_.head(10)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0.0
1,4.9,3.0,1.4,0.2,0.0
2,4.7,3.2,1.3,0.2,0.0
3,4.6,3.1,1.5,0.2,0.0
4,5.0,3.6,1.4,0.2,0.0
5,5.4,3.9,1.7,0.4,0.0
6,4.6,3.4,1.4,0.3,0.0
7,5.0,3.4,1.5,0.2,0.0
8,4.4,2.9,1.4,0.2,0.0
9,4.9,3.1,1.5,0.1,0.0

In [28]:
data_[['sepal length (cm)','target']].head()

   sepal length (cm)  target
0                5.1     0.0
1                4.9     0.0
2                4.7     0.0
3                4.6     0.0
4                5.0     0.0

## Now try to implement the functions from pandas official doc link above and try to learn attributes of pandas