In [1]:
pwd

'C:\\Users\\user\\OneDrive\\Desktop\\scatter-plotter\\Datacamp'

In [2]:
cd C:\\Users\\user\\OneDrive\\Desktop\\CSV files

C:\Users\user\OneDrive\Desktop\CSV files

In [3]:
import pandas as pd
import numpy as np

# Stanford Open Policing Project dataset

In [4]:
ri = pd.read_csv('RI_cleaned.csv')
ri

c:\python\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (8,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,id,state,stop_date,stop_time,location_raw,county_name,county_fips,fine_grained_location,police_department,driver_gender,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
0,RI-2005-00001,RI,2005-01-02,01:55,Zone K1,NaN,NaN,NaN,600,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1
1,RI-2005-00002,RI,2005-01-02,20:30,Zone X4,NaN,NaN,NaN,500,M,...,False,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4
2,RI-2005-00003,RI,2005-01-04,11:30,Zone X1,NaN,NaN,NaN,0,NaN,...,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,Zone X1
3,RI-2005-00004,RI,2005-01-04,12:55,Zone X4,NaN,NaN,NaN,500,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
4,RI-2005-00005,RI,2005-01-06,01:30,Zone X4,NaN,NaN,NaN,500,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
5,RI-2005-00006,RI,2005-01-12,08:05,Zone X1,NaN,NaN,NaN,0,M,...,False,NaN,NaN,False,Citation,False,30+ Min,True,False,Zone X1
6,RI-2005-00007,RI,2005-01-18,08:15,Zone K3,NaN,NaN,NaN,300,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
7,RI-2005-00008,RI,2005-01-18,17:13,Zone X1,NaN,NaN,NaN,0,M,...,False,NaN,NaN,False,Citation,False,16-30 Min,True,False,Zone X1
8,RI-2005-00009,RI,2005-01-23,23:15,Zone K3,NaN,NaN,NaN,300,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
9,RI-2005-00010,RI,2005-01-24,20:32,Zone K1,NaN,NaN,NaN,600,M,...,True,Probable Cause,Probable Cause,True,Citation,False,0-15 Min,True,True,Zone K1
10,RI-2005-00011,RI,2005-02-09,03:05,Zone X4,NaN,NaN,NaN,500,M,...,True,"Probable Cause,Terry Frisk","Probable Cause,Protective Frisk",False,Citation,False,0-15 Min,False,False,Zone X4
11,RI-2005-00012,RI,2005-02-11,01:20,Zone K3,NaN,NaN,NaN,300,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
12,RI-2005-00013,RI,2005-02-11,02:45,Zone K3,NaN,NaN,NaN,300,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3
13,RI-2005-00014,RI,2005-02-17,04:15,Zone X4,NaN,NaN,NaN,500,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
14,RI-2005-00015,RI,2005-02-20,17:15,Zone X1,NaN,NaN,NaN,0,M,...,False,NaN,NaN,False,Arrest Driver,True,16-30 Min,True,False,Zone X1
15,RI-2005-00016,RI,2005-02-24,01:20,Zone X3,NaN,NaN,NaN,200,F,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone X3
16,RI-2005-00017,RI,2005-02-24,05:50,Zone X3,NaN,NaN,NaN,200,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X3
17,RI-2005-00018,RI,2005-03-05,00:20,Zone X4,NaN,NaN,NaN,500,NaN,...,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,Zone X4
18,RI-2005-00019,RI,2005-03-14,10:00,Zone K3,NaN,NaN,NaN,300,F,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3
19,RI-2005-00020,RI,2005-03-16,12:05,Zone X1,NaN,NaN,NaN,0,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X1
20,RI-2005-00021,RI,2005-03-16,15:15,Zone K3,NaN,NaN,NaN,300,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3
21,RI-2005-00022,RI,2005-03-19,14:15,Zone K2,NaN,NaN,NaN,900,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K2
22,RI-2005-00023,RI,2005-03-23,09:45,Zone X4,NaN,NaN,NaN,500,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
23,RI-2005-00024,RI,2005-03-29,00:05,Zone K3,NaN,NaN,NaN,300,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
24,RI-2005-00025,RI,2005-03-29,21:55,Zone K3,NaN,NaN,NaN,300,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
25,RI-2005-00026,RI,2005-03-29,23:20,Zone K3,NaN,NaN,NaN,300,F,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
26,RI-2005-00027,RI,2005-03-30,22:45,Zone K3,NaN,NaN,NaN,300,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
27,RI-2005-00028,RI,2005-03-30,23:35,Zone K3,NaN,NaN,NaN,300,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
28,RI-2005-00029,RI,2005-04-01,17:30,Zone K1,NaN,NaN,NaN,600,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K1
29,RI-2005-00030,RI,2005-04-04,21:25,Zone K1,NaN,NaN,NaN,600,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509651,RI-2015-47046,RI,2015-12-31,21:03,Zone X3,NaN,NaN,NaN,200,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone X3
509652,RI-2015-47047,RI,2015-12-31,21:21,Zone K2,NaN,NaN,NaN,900,F,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K2
509653,RI-2015-47048,RI,2015-12-31,21:32,Zone X3,NaN,NaN,NaN,200,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X3
509654,RI-2015-47049,RI,2015-12-31,21:42,Zone X1,NaN,NaN,NaN,0,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone X1
509655,RI-2015-47050,RI,2015-12-31,21:47,Zone K3,NaN,NaN,NaN,300,F,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
509656,RI-2015-47051,RI,2015-12-31,21:59,Zone K3,NaN,NaN,NaN,300,F,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3
509657,RI-2015-47052,RI,2015-12-31,21:59,Zone X1,NaN,NaN,NaN,0,NaN,...,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,Zone X1
509658,RI-2015-47053,RI,2015-12-31,22:04,Zone X3,NaN,NaN,NaN,200,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X3
509659,RI-2015-47054,RI,2015-12-31,22:09,Zone K3,NaN,NaN,NaN,300,F,...,False,NaN,NaN,False,Warning,False,0-15 Min,False,False,Zone K3
509660,RI-2015-47055,RI,2015-12-31,22:10,Zone X4,NaN,NaN,NaN,300,F,...,False,NaN,NaN,False,Warning,False,0-15 Min,False,False,Zone X4
509661,RI-2015-47056,RI,2015-12-31,22:10,Zone X4,NaN,NaN,NaN,300,F,...,False,NaN,NaN,False,Arrest Driver,True,0-15 Min,False,False,Zone X4
509662,RI-2015-47057,RI,2015-12-31,22:14,Zone X4,NaN,NaN,NaN,500,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone X4
509663,RI-2015-47058,RI,2015-12-31,22:26,Zone K3,NaN,NaN,NaN,300,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
509664,RI-2015-47059,RI,2015-12-31,22:38,Zone X4,NaN,NaN,NaN,500,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone X4
509665,RI-2015-47060,RI,2015-12-31,22:39,Zone K3,NaN,NaN,NaN,300,F,...,False,NaN,NaN,False,Citation,False,16-30 Min,True,False,Zone K3
509666,RI-2015-47061,RI,2015-12-31,22:46,Zone X1,NaN,NaN,NaN,0,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone X1
509667,RI-2015-47062,RI,2015-12-31,22:47,Zone X4,NaN,NaN,NaN,500,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
509668,RI-2015-47063,RI,2015-12-31,23:08,Zone X3,NaN,NaN,NaN,200,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X3
509669,RI-2015-47064,RI,2015-12-31,23:44,Zone K2,NaN,NaN,NaN,900,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K2
509670,RI-2015-47065,RI,2015-12-31,23:48,Zone K3,NaN,NaN,NaN,300,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3
509671,RI-NA-01,RI,NaN,NaN,Zone NA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False,Zone NA
509672,RI-NA-02,RI,NaN,NaN,Zone NA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False,Zone NA
509673,RI-NA-03,RI,NaN,NaN,Zone NA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False,Zone NA
509674,RI-NA-04,RI,NaN,NaN,Zone NA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False,Zone NA
509675,RI-NA-05,RI,NaN,NaN,Zone NA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False,Zone NA
509676,RI-NA-06,RI,NaN,NaN,Zone NA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False,Zone NA
509677,RI-NA-07,RI,NaN,NaN,Zone NA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False,Zone NA
509678,RI-NA-08,RI,NaN,NaN,Zone NA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False,Zone NA
509679,RI-NA-09,RI,NaN,NaN,Zone NA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False,Zone NA
509680,RI-NA-10,RI,NaN,NaN,Zone NA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False,Zone NA

In [5]:
# examine the data
ri.head()

,id,state,stop_date,stop_time,location_raw,county_name,county_fips,fine_grained_location,police_department,driver_gender,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
0,RI-2005-00001,RI,2005-01-02,01:55,Zone K1,NaN,NaN,NaN,600,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1
1,RI-2005-00002,RI,2005-01-02,20:30,Zone X4,NaN,NaN,NaN,500,M,...,False,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4
2,RI-2005-00003,RI,2005-01-04,11:30,Zone X1,NaN,NaN,NaN,0,NaN,...,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,Zone X1
3,RI-2005-00004,RI,2005-01-04,12:55,Zone X4,NaN,NaN,NaN,500,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
4,RI-2005-00005,RI,2005-01-06,01:30,Zone X4,NaN,NaN,NaN,500,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4

In [6]:
ri.isnull().sum()

id                            0
state                         0
stop_date                    10
stop_time                    10
location_raw                  0
county_name              509681
county_fips              509681
fine_grained_location    509681
police_department            10
driver_gender             29097
driver_age_raw            29049
driver_age                30695
driver_race_raw           29073
driver_race               29073
violation_raw             29073
violation                 29073
search_conducted             10
search_type_raw          491919
search_type              491919
contraband_found              0
stop_outcome              29073
is_arrested               29073
stop_duration             29073
out_of_state              29881
drugs_related_stop            0
district                      0
dtype: int64

In [8]:
# dropping column
# Count the number of missing values in each column
print(ri.isnull().sum())
# Examine the shape of the DataFrame
print(ri.shape)
# Examine the shape of the DataFrame (again)
print(ri.shape)

id                            0
state                         0
stop_date                    10
stop_time                    10
location_raw                  0
county_name              509681
county_fips              509681
fine_grained_location    509681
police_department            10
driver_gender             29097
driver_age_raw            29049
driver_age                30695
driver_race_raw           29073
driver_race               29073
violation_raw             29073
violation                 29073
search_conducted             10
search_type_raw          491919
search_type              491919
contraband_found              0
stop_outcome              29073
is_arrested               29073
stop_duration             29073
out_of_state              29881
drugs_related_stop            0
district                      0
dtype: int64
(509681, 26)
(509681, 26)

In [9]:
# dropping rows
# Drop all rows that are missing 'driver_gender'
ri.dropna(subset=["driver_gender"], inplace=True)

# Count the number of missing values in each column (again)
print(ri.isnull().sum())

# Examine the shape of the DataFrame
print(ri.shape)

id                            0
state                         0
stop_date                     0
stop_time                     0
location_raw                  0
county_name              480584
county_fips              480584
fine_grained_location    480584
police_department             0
driver_gender                 0
driver_age_raw                1
driver_age                 1638
driver_race_raw               0
driver_race                   0
violation_raw                 0
violation                     0
search_conducted              0
search_type_raw          462822
search_type              462822
contraband_found              0
stop_outcome                  0
is_arrested                   0
stop_duration                 0
out_of_state                808
drugs_related_stop            0
district                      0
dtype: int64
(480584, 26)

In [10]:
# fixing a datatype
# Examine the head of the 'is_arrested' column
print(ri.is_arrested.head())

# Check the data type of 'is_arrested'
print(ri.is_arrested.dtype)

# Change the data type of 'is_arrested' to 'bool'
ri['is_arrested'] = ri.is_arrested.astype('bool')

# Check the data type of 'is_arrested' (again)
print(ri.is_arrested.dtype)

0    False
1    False
3    False
4    False
5    False
Name: is_arrested, dtype: object
object
bool

In [11]:
# combining object columns
# Concatenate 'stop_date' and 'stop_time' (separated by a space)
combined = ri.stop_date.str.cat(ri.stop_time, sep= ' ')   

# Convert 'combined' to datetime format
ri['stop_datetime'] = pd.to_datetime(combined)

# Examine the data types of the DataFrame
print(ri.dtypes)

id                               object
state                            object
stop_date                        object
stop_time                        object
location_raw                     object
county_name                     float64
county_fips                     float64
fine_grained_location           float64
police_department                object
driver_gender                    object
driver_age_raw                  float64
driver_age                      float64
driver_race_raw                  object
driver_race                      object
violation_raw                    object
violation                        object
search_conducted                 object
search_type_raw                  object
search_type                      object
contraband_found                   bool
stop_outcome                     object
is_arrested                        bool
stop_duration                    object
out_of_state                     object
drugs_related_stop                 bool
district                         object
stop_datetime            datetime64[ns]
dtype: object

In [12]:
# setting the index
# Set 'stop_datetime' as the index
ri.set_index('stop_datetime', inplace=True)

# Examine the index
print(ri.index)

# Examine the columns
print(ri.columns)

DatetimeIndex(['2005-01-02 01:55:00', '2005-01-02 20:30:00',
               '2005-01-04 12:55:00', '2005-01-06 01:30:00',
               '2005-01-12 08:05:00', '2005-01-18 08:15:00',
               '2005-01-18 17:13:00', '2005-01-23 23:15:00',
               '2005-01-24 20:32:00', '2005-02-09 03:05:00',
               ...
               '2015-12-31 22:10:00', '2015-12-31 22:14:00',
               '2015-12-31 22:26:00', '2015-12-31 22:38:00',
               '2015-12-31 22:39:00', '2015-12-31 22:46:00',
               '2015-12-31 22:47:00', '2015-12-31 23:08:00',
               '2015-12-31 23:44:00', '2015-12-31 23:48:00'],
              dtype='datetime64[ns]', name='stop_datetime', length=480584, freq=None)
Index(['id', 'state', 'stop_date', 'stop_time', 'location_raw', 'county_name',
       'county_fips', 'fine_grained_location', 'police_department',
       'driver_gender', 'driver_age_raw', 'driver_age', 'driver_race_raw',
       'driver_race', 'violation_raw', 'violation', 'search_conducted',
       'search_type_raw', 'search_type', 'contraband_found', 'stop_outcome',
       'is_arrested', 'stop_duration', 'out_of_state', 'drugs_related_stop',
       'district'],
      dtype='object')

In [13]:
# Exploring the relationship between gender and policing
# Count the unique values in 'violation'
display(ri.violation.value_counts())

# Express the counts as proportions
display(ri.violation.value_counts(normalize=True))

Speeding               268736
Moving violation        90228
Equipment               61250
Other                   24216
Registration/plates     19830
Seat belt               16324
Name: violation, dtype: int64

Speeding               0.559186
Moving violation       0.187747
Equipment              0.127449
Other                  0.050389
Registration/plates    0.041262
Seat belt              0.033967
Name: violation, dtype: float64

In [14]:
# Comparing violations by gender
# Create a DataFrame of female drivers
female = ri[ri.driver_gender == 'F']

# Create a DataFrame of male drivers
male = ri[ri.driver_gender == 'M']

# Compute the violations by female drivers (as proportions)
print(female.violation.value_counts(normalize=True))

# Compute the violations by male drivers (as proportions)
print(male.violation.value_counts(normalize=True))

Speeding               0.657308
Moving violation       0.136581
Equipment              0.107055
Registration/plates    0.043077
Other                  0.028908
Seat belt              0.027071
Name: violation, dtype: float64
Speeding               0.522364
Moving violation       0.206948
Equipment              0.135102
Other                  0.058450
Registration/plates    0.040581
Seat belt              0.036555
Name: violation, dtype: float64

In [15]:
# Comparing speeding outcomes by gender
# Create a DataFrame of female drivers stopped for speeding
female_and_speeding = ri[(ri.driver_gender == 'F') & (ri.violation == 'Speeding')]

# Create a DataFrame of male drivers stopped for speeding
male_and_speeding = ri[(ri.driver_gender == 'M') & (ri.violation == 'Speeding')]

# Compute the stop outcomes for female drivers (as proportions)
print(female_and_speeding.stop_outcome.value_counts(normalize=True))

# Compute the stop outcomes for male drivers (as proportions)
print(male_and_speeding.stop_outcome.value_counts(normalize=True))

Citation            0.953247
Warning             0.039003
Arrest Driver       0.005290
Arrest Passenger    0.001033
N/D                 0.000905
No Action           0.000522
Name: stop_outcome, dtype: float64
Citation            0.944636
Warning             0.036086
Arrest Driver       0.015767
Arrest Passenger    0.001265
N/D                 0.001183
No Action           0.001063
Name: stop_outcome, dtype: float64

In [16]:
# Calculating the search rate

# Check the data type of 'search_conducted'
print(ri.search_conducted.dtype)

# Calculate the search rate by counting the values
print(ri.search_conducted.value_counts(normalize=True))

# Calculate the search rate by taking the mean
print(ri.search_conducted.mean())

object
False    0.963041
True     0.036959
Name: search_conducted, dtype: float64
0.036959199640437465

In [17]:
# Comparing search rates by gender
print(ri[ri.driver_gender == 'F'].search_conducted.mean())

0.018751239152648355

In [19]:
ri['search_conducted'] = ri.search_conducted.astype('bool')

In [20]:
# Calculate the search rate for male drivers
print(ri[ri.driver_gender == 'M'].search_conducted.mean())

0.04379217389811301

In [21]:
# Calculate the search rate for both groups simultaneously
ri.groupby('driver_gender').search_conducted.mean()

driver_gender
F    0.018751
M    0.043792
Name: search_conducted, dtype: float64

In [23]:
# Adding a second factor to the analysis
# Calculate the search rate for each combination of gender and violation
print(ri.groupby(['driver_gender', 'violation']).search_conducted.mean())

driver_gender  violation
F              Equipment              0.040245
               Moving violation       0.038021
               Other                  0.045898
               Registration/plates    0.054700
               Seat belt              0.017746
               Speeding               0.007738
M              Equipment              0.070916
               Moving violation       0.059156
               Other                  0.046120
               Registration/plates    0.103589
               Seat belt              0.031705
               Speeding               0.026630
Name: search_conducted, dtype: float64

In [24]:
# Reverse the ordering to group by violation before gender
print(ri.groupby(['violation', 'driver_gender']).search_conducted.mean())

violation            driver_gender
Equipment            F                0.040245
                     M                0.070916
Moving violation     F                0.038021
                     M                0.059156
Other                F                0.045898
                     M                0.046120
Registration/plates  F                0.054700
                     M                0.103589
Seat belt            F                0.017746
                     M                0.031705
Speeding             F                0.007738
                     M                0.026630
Name: search_conducted, dtype: float64

In [25]:
# Counting protective frisks
# Count the 'search_type' values
print(ri.search_type.value_counts(dropna=False))

# Check if 'search_type' contains the string 'Protective Frisk'
ri['frisk'] = ri.search_type.str.contains('Protective Frisk', na=False) ######## CONTAINS

# Check the data type of 'frisk'
print(ri.frisk.dtype)

# Take the sum of 'frisk'
print(ri.frisk.sum())

NaN                                                         462822
Incident to Arrest                                            6998
Probable Cause                                                4989
Reasonable Suspicion                                          1141
Inventory                                                     1101
Protective Frisk                                               879
Incident to Arrest,Inventory                                   649
Incident to Arrest,Probable Cause                              552
Probable Cause,Reasonable Suspicion                            334
Probable Cause,Protective Frisk                                221
Incident to Arrest,Protective Frisk                            158
Incident to Arrest,Inventory,Probable Cause                    151
Inventory,Probable Cause                                       132
Protective Frisk,Reasonable Suspicion                           83
Incident to Arrest,Inventory,Protective Frisk                   77
Incident to Arrest,Probable Cause,Protective Frisk              74
Inventory,Protective Frisk                                      52
Incident to Arrest,Reasonable Suspicion                         49
Incident to Arrest,Probable Cause,Reasonable Suspicion          31
Probable Cause,Protective Frisk,Reasonable Suspicion            31
Inventory,Reasonable Suspicion                                  17
Inventory,Probable Cause,Protective Frisk                       14
Incident to Arrest,Inventory,Reasonable Suspicion               12
Incident to Arrest,Protective Frisk,Reasonable Suspicion         8
Inventory,Probable Cause,Reasonable Suspicion                    8
Inventory,Protective Frisk,Reasonable Suspicion                  1
Name: search_type, dtype: int64
bool
1598

In [26]:
# Comparing frisk rates by gender

# Create a DataFrame of stops in which a search was conducted
searched = ri[ri.search_conducted == True]

# Calculate the overall frisk rate by taking the mean of 'frisk'
print(searched.frisk.mean())

# Calculate the frisk rate for each gender
print(searched.groupby('driver_gender').frisk.mean())

0.08996734601959239
driver_gender
F    0.066694
M    0.093707
Name: frisk, dtype: float64

In [27]:
# Visual exploratory data analysis