In [1]:
pwd

'C:\\Users\\user\\OneDrive\\Desktop\\scatter-plotter\\Datacamp'

In [2]:
cd C:\\Users\\user\\OneDrive\\Desktop\\CSV files

C:\Users\user\OneDrive\Desktop\CSV files

In [3]:
import pandas as pd
import numpy as np

# Stanford Open Policing Project dataset

In [4]:
ri = pd.read_csv('police2.csv')
ri

c:\python\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (3,13,14,15,16,17,18,19,20,21,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,raw_row_number,date,time,location,lat,lng,district,zone,subject_age,subject_race,...,frisk_performed,search_conducted,search_person,search_vehicle,search_basis,reason_for_stop,vehicle_color,vehicle_make,vehicle_model,vehicle_year
0,1,2010-01-01,01:11:00,NaN,NaN,NaN,6,E,26.0,black,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,BLACK,DODGE,CARAVAN,2005.0
1,2,2010-01-01,02:06:00,NaN,NaN,NaN,5,D,17.0,black,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,NaN,NaN,NaN,NaN
2,3,2010-01-01,02:06:00,NaN,NaN,NaN,5,D,18.0,black,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,NaN,NaN,NaN,NaN
3,4,2010-01-01,02:06:00,NaN,NaN,NaN,5,D,30.0,black,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,NaN,NaN,NaN,NaN
4,5,2010-01-01,02:06:00,NaN,NaN,NaN,5,D,21.0,black,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,NaN,NaN,NaN,NaN
5,6,2010-01-01,02:06:00,NaN,NaN,NaN,5,D,20.0,black,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,NaN,NaN,NaN,NaN
6,7,2010-01-01,02:06:00,NaN,NaN,NaN,5,D,18.0,black,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,NaN,NaN,NaN,NaN
7,8,2010-01-01,02:06:00,NaN,NaN,NaN,5,D,23.0,black,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,NaN,NaN,NaN,NaN
8,9,2009-12-31,22:23:00,NaN,NaN,NaN,5,L,17.0,black,...,NaN,NaN,NaN,NaN,NaN,CRIMINAL VIOLATION,NaN,NaN,NaN,NaN
9,10,2010-01-01,07:54:00,NaN,NaN,NaN,6,I,54.0,black,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,GREEN,TOYOTA,NaN,1995.0
10,11,2010-01-01,07:56:00,NaN,NaN,NaN,6,J,66.0,black,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,BRONZE,PONTIAC,GRAND PRIX,2006.0
11,12,2010-01-01,08:02:00,NaN,NaN,NaN,6,D,47.0,white,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,NaN,NaN,NaN,NaN
12,13,2010-01-01,09:29:00,NaN,NaN,NaN,6,F,31.0,black,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,WHITE,FORD,NaN,2000.0
13,14,2010-01-01,08:48:00,NaN,NaN,NaN,3,D,59.0,white,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,WHITE,CHEVROLET,PICKUP,2000.0
14,15,2010-01-01,12:46:00,NaN,NaN,NaN,6,F,27.0,hispanic,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,BLACK,ACURA,LEGEND,1996.0
15,16,2010-01-01,17:09:00,NaN,NaN,NaN,8,C,42.0,black,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,YELLOW,CHEVROLET,SUBURBAN,NaN
16,17,2009-10-27,20:49:00,NaN,NaN,NaN,7,H,23.0,black,...,NaN,NaN,NaN,NaN,NaN,SUSPECT PERSON,NaN,NaN,NaN,NaN
17,18,2009-10-27,14:06:00,NaN,NaN,NaN,7,F,17.0,black,...,NaN,NaN,NaN,NaN,NaN,SUSPECT PERSON,NaN,NaN,NaN,NaN
18,19,2009-10-25,01:01:00,NaN,NaN,NaN,7,C,25.0,black,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,NaN,NaN,NaN,NaN
19,20,2009-10-26,18:56:00,NaN,NaN,NaN,7,H,41.0,white,...,NaN,NaN,NaN,NaN,NaN,SUSPECT PERSON,NaN,NaN,NaN,NaN
20,21,2009-12-31,03:00:00,NaN,NaN,NaN,7,Q,53.0,black,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,NaN,MAZDA,MAZDA6,2000.0
21,22,2009-12-11,11:12:00,NaN,NaN,NaN,7,I,20.0,black,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,WHITE,PONTIAC,GRAND PRIX,2004.0
22,23,2009-12-29,08:13:00,NaN,NaN,NaN,7,O,43.0,black,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,WHITE,GMC - GENERAL MOTORS CORP.,NaN,2003.0
23,24,2010-01-01,21:06:00,NaN,NaN,NaN,5,B,55.0,black,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,WHITE,DODGE,RAM,1996.0
24,25,2009-12-29,07:43:00,NaN,NaN,NaN,7,D,28.0,black,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,RED,DODGE,NEON,2002.0
25,26,2010-01-01,21:16:00,NaN,NaN,NaN,5,B,17.0,black,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,WHITE,DODGE,RAM,1996.0
26,27,2010-01-01,16:03:00,NaN,NaN,NaN,6,F,32.0,black,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,BLUE,GMC - GENERAL MOTORS CORP.,OTHER,1997.0
27,28,2010-01-01,16:03:00,NaN,NaN,NaN,6,F,28.0,black,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,BLUE,GMC - GENERAL MOTORS CORP.,OTHER,1997.0
28,29,2011-01-26,17:08:00,NaN,NaN,NaN,8,A,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,NaN,NaN,NaN,NaN
29,30,2010-12-31,21:09:00,NaN,NaN,NaN,6,F,25.0,black,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,BLACK,NISSAN,MAXIMA,2009.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
513035,513036,2018-07-17,21:34:00,067XX Bundy Rd,NaN,NaN,7,R,32.0,black,...,False,True,True,False,other,CRIMINAL VIOLATION,NaN,NaN,NaN,NaN
513036,513037,2018-07-17,21:30:00,Chef Menteur Hwy & Downman Rd,30.009886,-90.020917,7,A,25.0,black,...,False,False,True,True,NaN,TRAFFIC VIOLATION,BLUE,CHEVROLET,OTHER,2008.0
513037,513038,2018-07-17,00:00:00,Florida Ave & Elysian Fields Ave,29.991471,-90.077763,5,K,33.0,white,...,False,True,True,True,other,TRAFFIC VIOLATION,GRAY,CHEVROLET,TAHOE,2002.0
513038,513039,2018-07-17,22:12:00,Saint Claude Ave & Franklin Ave,29.968932,-90.050107,5,B,37.0,white,...,False,False,True,True,NaN,TRAFFIC VIOLATION,BLACK,CHEVROLET,TAHOE,2012.0
513039,513040,2018-07-17,21:55:00,Chef Menteur Hwy & Downman Rd,30.009886,-90.020917,7,A,23.0,black,...,False,False,True,True,NaN,TRAFFIC VIOLATION,BLACK,CHEVROLET,IMPALA,2014.0
513040,513041,2018-07-17,21:17:00,Chef Menteur Hwy & Downman Rd,30.009886,-90.020917,7,A,31.0,black,...,False,False,True,True,NaN,TRAFFIC VIOLATION,SILVER,KIA (4-WHEEL AUTOMOBILE),OTHER,2010.0
513041,513042,2018-07-17,22:19:00,Saint Claude Ave & Franklin Ave,29.968932,-90.050107,5,B,27.0,white,...,False,False,True,True,NaN,TRAFFIC VIOLATION,BLACK,INFINITY,OTHER,2017.0
513042,513043,2018-07-17,20:19:00,Chef Menteur Hwy & Downman Rd,30.009886,-90.020917,7,A,43.0,black,...,False,False,True,True,NaN,TRAFFIC VIOLATION,GRAY,NISSAN,ALTIMA,2006.0
513043,513044,2018-07-17,20:15:00,Chef Menteur Hwy & Downman Rd,30.009886,-90.020917,7,A,28.0,black,...,False,False,True,True,NaN,TRAFFIC VIOLATION,BLACK,TOYOTA,CELICA,2003.0
513044,513045,2018-07-17,20:30:00,Chef Menteur Hwy & Downman Rd,30.009886,-90.020917,7,A,20.0,black,...,False,False,True,True,NaN,TRAFFIC VIOLATION,TAN,NISSAN,ALTIMA,2005.0
513045,513046,2018-07-17,21:00:00,Chef Menteur Hwy & Downman Rd,30.009886,-90.020917,7,A,37.0,black,...,False,False,True,True,NaN,TRAFFIC VIOLATION,WHITE,CHEVROLET,SILVERADO,2004.0
513046,513047,2018-07-16,15:10:00,022XX State St,NaN,NaN,2,K,23.0,hispanic,...,True,True,True,True,other,TRAFFIC VIOLATION,BLUE,GMC - GENERAL MOTORS CORP.,OTHER,2007.0
513047,513048,2018-07-17,22:48:00,Saint Claude Ave & Franklin Ave,29.968932,-90.050107,5,B,33.0,white,...,False,False,True,True,NaN,TRAFFIC VIOLATION,WHITE,TOYOTA,TUNDRA,2017.0
513048,513049,2018-07-17,19:52:00,Louisiana Avenue Pkwy & S Broad St,29.950495,-90.101281,2,R,26.0,black,...,False,False,True,True,NaN,TRAFFIC VIOLATION,GRAY,INFINITY,OTHER,2004.0
513049,513050,2018-07-13,16:49:00,060XX Tullis Dr,NaN,NaN,4,E,42.0,black,...,False,True,True,False,other,CALL FOR SERVICE,NaN,NaN,NaN,NaN
513050,513051,2018-07-17,20:30:00,Chef Menteur Hwy & Downman Rd,30.009886,-90.020917,7,A,34.0,black,...,False,False,True,True,NaN,TRAFFIC VIOLATION,BLACK,KIA (4-WHEEL AUTOMOBILE),OTHER,2011.0
513051,513052,2018-07-17,23:27:00,Eastview Dr & Chef Menteur Hwy,30.013484,-89.991955,7,F,18.0,black,...,False,False,True,True,NaN,TRAFFIC VIOLATION,PURPLE,CHEVROLET,OTHER,2006.0
513052,513053,2018-07-17,23:27:00,S Jefferson Davis Pkwy & Earhart Blvd,29.956889,-90.105378,2,T,23.0,black,...,False,False,True,True,NaN,TRAFFIC VIOLATION,BLACK,MERCEDES-BENZ,OTHER,2016.0
513053,513054,2018-07-17,23:27:00,S Jefferson Davis Pkwy & Earhart Blvd,29.956889,-90.105378,2,T,29.0,black,...,False,False,True,True,NaN,TRAFFIC VIOLATION,BLACK,MERCEDES-BENZ,OTHER,2016.0
513054,513055,2018-07-17,23:27:00,S Jefferson Davis Pkwy & Earhart Blvd,29.956889,-90.105378,2,T,23.0,black,...,False,False,True,True,NaN,TRAFFIC VIOLATION,BLACK,MERCEDES-BENZ,OTHER,2016.0
513055,513056,2018-07-17,23:27:00,S Jefferson Davis Pkwy & Earhart Blvd,29.956889,-90.105378,2,T,24.0,black,...,False,False,True,True,NaN,TRAFFIC VIOLATION,BLACK,MERCEDES-BENZ,OTHER,2016.0
513056,513057,2018-07-17,23:31:00,Chef Menteur Hwy & Downman Rd,30.009886,-90.020917,7,A,18.0,black,...,False,False,True,True,NaN,TRAFFIC VIOLATION,BEIGE,KIA (4-WHEEL AUTOMOBILE),OTHER,2017.0
513057,513058,2018-07-17,20:43:00,Chef Menteur Hwy & Downman Rd,30.009886,-90.020917,7,A,24.0,black,...,False,False,True,True,NaN,TRAFFIC VIOLATION,GRAY,CHEVROLET,OTHER,2017.0
513058,513059,2018-07-17,20:59:00,Chef Menteur Hwy & Downman Rd,30.009886,-90.020917,7,A,42.0,black,...,False,False,True,True,NaN,TRAFFIC VIOLATION,SILVER,CHEVROLET,OTHER,2017.0
513059,513060,2018-07-17,23:20:00,022XX Springbrook Ln,NaN,NaN,4,J,30.0,black,...,False,True,True,False,other,CRIMINAL VIOLATION,NaN,NaN,NaN,NaN
513060,513061,2018-07-11,23:56:00,003XX N Rampart St,NaN,NaN,1,E,27.0,black,...,True,False,True,True,NaN,TRAFFIC VIOLATION,BLACK,HONDA,ACCORD,2013.0
513061,513062,2018-07-11,23:56:00,003XX N Rampart St,NaN,NaN,1,E,44.0,white,...,False,False,True,True,NaN,TRAFFIC VIOLATION,BLACK,HONDA,ACCORD,2013.0
513062,513063,2018-07-18,00:07:00,002XX Bourbon St,NaN,NaN,8,C,37.0,black,...,False,False,True,False,NaN,CRIMINAL VIOLATION,NaN,NaN,NaN,NaN
513063,513064,2018-07-18,00:00:00,NaN,NaN,NaN,8,D,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,CRIMINAL VIOLATION,NaN,NaN,NaN,NaN
513064,513065,2018-07-18,00:34:00,N Claiborne Ave & Saint Louis St,29.962189,-90.074753,1,E,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,NaN,NaN,NaN,NaN

In [5]:
# examine the data
ri.head()

,raw_row_number,date,time,location,lat,lng,district,zone,subject_age,subject_race,...,frisk_performed,search_conducted,search_person,search_vehicle,search_basis,reason_for_stop,vehicle_color,vehicle_make,vehicle_model,vehicle_year
0,1,2010-01-01,01:11:00,NaN,NaN,NaN,6,E,26.0,black,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,BLACK,DODGE,CARAVAN,2005.0
1,2,2010-01-01,02:06:00,NaN,NaN,NaN,5,D,17.0,black,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,NaN,NaN,NaN,NaN
2,3,2010-01-01,02:06:00,NaN,NaN,NaN,5,D,18.0,black,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,NaN,NaN,NaN,NaN
3,4,2010-01-01,02:06:00,NaN,NaN,NaN,5,D,30.0,black,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,NaN,NaN,NaN,NaN
4,5,2010-01-01,02:06:00,NaN,NaN,NaN,5,D,21.0,black,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,NaN,NaN,NaN,NaN

In [6]:
ri.isnull().sum()

raw_row_number             0
date                      10
time                       0
location               96644
lat                   252441
lng                   252441
district                   0
zone                       0
subject_age            13185
subject_race           12127
subject_sex            12127
officer_assignment       124
type                  150149
arrest_made           123349
citation_issued       123349
warning_issued        123349
outcome               177385
contraband_found      437263
contraband_drugs      437263
contraband_weapons    437263
frisk_performed       123349
search_conducted      123349
search_person         123349
search_vehicle        123349
search_basis          437263
reason_for_stop            0
vehicle_color         239498
vehicle_make          236111
vehicle_model         253379
vehicle_year          240697
dtype: int64

In [7]:
ri.outcome.value_counts()

warning     123851
citation    117650
arrest       94179
Name: outcome, dtype: int64

In [8]:
ri.outcome.value_counts().sum()

335680

In [9]:
ri.head()

,raw_row_number,date,time,location,lat,lng,district,zone,subject_age,subject_race,...,frisk_performed,search_conducted,search_person,search_vehicle,search_basis,reason_for_stop,vehicle_color,vehicle_make,vehicle_model,vehicle_year
0,1,2010-01-01,01:11:00,NaN,NaN,NaN,6,E,26.0,black,...,NaN,NaN,NaN,NaN,NaN,TRAFFIC VIOLATION,BLACK,DODGE,CARAVAN,2005.0
1,2,2010-01-01,02:06:00,NaN,NaN,NaN,5,D,17.0,black,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,NaN,NaN,NaN,NaN
2,3,2010-01-01,02:06:00,NaN,NaN,NaN,5,D,18.0,black,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,NaN,NaN,NaN,NaN
3,4,2010-01-01,02:06:00,NaN,NaN,NaN,5,D,30.0,black,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,NaN,NaN,NaN,NaN
4,5,2010-01-01,02:06:00,NaN,NaN,NaN,5,D,21.0,black,...,NaN,NaN,NaN,NaN,NaN,CALL FOR SERVICE,NaN,NaN,NaN,NaN

In [10]:
ri.dtypes

raw_row_number          int64
date                   object
time                   object
location               object
lat                   float64
lng                   float64
district                int64
zone                   object
subject_age           float64
subject_race           object
subject_sex            object
officer_assignment     object
type                   object
arrest_made            object
citation_issued        object
warning_issued         object
outcome                object
contraband_found       object
contraband_drugs       object
contraband_weapons     object
frisk_performed        object
search_conducted       object
search_person          object
search_vehicle         object
search_basis           object
reason_for_stop        object
vehicle_color          object
vehicle_make           object
vehicle_model          object
vehicle_year          float64
dtype: object

In [11]:
ri.shape

(513065, 30)

In [12]:
117650/335680

0.350482602478551

In [13]:
ri.outcome.value_counts(normalize=True)

warning     0.368956
citation    0.350483
arrest      0.280562
Name: outcome, dtype: float64

In [14]:
# filtering data frame rows
ri.subject_race.value_counts()

black                     350283
white                     129767
hispanic                   13517
asian/pacific islander      3810
other/unknown               3561
Name: subject_race, dtype: int64

In [15]:
black = ri[ri.subject_race == 'black']

In [16]:
black.shape

(350283, 30)

In [17]:
black.outcome.value_counts(normalize=True)

warning     0.368637
citation    0.324616
arrest      0.306746
Name: outcome, dtype: float64

In [18]:
hispanic = ri[ri.subject_race == 'hispanic']

In [19]:
hispanic.shape

(13517, 30)

In [20]:
hispanic.outcome.value_counts(normalize=True)

citation    0.473988
warning     0.309868
arrest      0.216144
Name: outcome, dtype: float64

In [21]:
female = ri[ri.subject_sex == 'f']

In [22]:
female.shape

(0, 30)

In [23]:
ri.subject_sex.value_counts

<bound method IndexOpsMixin.value_counts of 0         female
1           male
2           male
3           male
4           male
5           male
6           male
7           male
8         female
9           male
10          male
11        female
12          male
13          male
14          male
15          male
16          male
17          male
18        female
19          male
20        female
21          male
22          male
23          male
24          male
25        female
26          male
27          male
28           NaN
29        female
           ...
513035      male
513036    female
513037      male
513038    female
513039      male
513040      male
513041      male
513042    female
513043      male
513044      male
513045      male
513046      male
513047      male
513048      male
513049      male
513050      male
513051      male
513052      male
513053      male
513054      male
513055      male
513056    female
513057    female
513058    female
513059      male
513060      male
513061      male
513062      male
513063       NaN
513064       NaN
Name: subject_sex, Length: 513065, dtype: object>